### PR TITLE
fix: grammar in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by joshuasorkin**
Added a missing "are" in the first paragraph of the contributing guidelines.

### CODE REVIEW

**Review by neekolas — APPROVED** [review]

**Comment by neekolas** [comment]
Thanks for catching this @joshuasorkin

**Comment by joshuasorkin** [comment]
Thanks @neekolas ! It says:
```
3 workflows awaiting approval
First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)
4 expected checks
```
Do I need to do something else on my end before we can merge this PR?

**Comment by elisealix22** [comment]
Approved the workflow to kick off the Actions so you should be all set @joshuasorkin ! Thanks again for this.

**Comment by joshuasorkin** [comment]
thanks @elisealix22 ! I don't have write access to the repo so I can't merge the PR.

**Pull request merged**
