### PR TITLE
fix: Fix deflate compression

### PR DESCRIPTION
**Pull request by nakajima**
Client.encodeContent was checking `options?.compression`, which in the case of `Compression.COMPRESSION_DEFLATE` equals `0`, which is falsey in JS.

### CODE REVIEW

**Review by mkobetic — APPROVED** [review]
Good catch. Thank you! ❤️

**Comment by nakajima** [comment]
@mkobetic Thanks for the review! I think I found another issue that I pushed a fix for in https://github.com/xmtp/xmtp-js/pull/261/commits/859ae756b9a0ef7504075c3ac74b9a7d12d9d6b7 if you don't mind taking a look at that as well.

**Comment by mkobetic** [comment]
> @mkobetic Thanks for the review! I think I found another issue that I pushed a fix for in [859ae75](https://github.com/xmtp/xmtp-js/commit/859ae756b9a0ef7504075c3ac74b9a7d12d9d6b7) if you don't mind taking a look at that as well.

Ouch, was this really completely broken for V2 messages? Seems that way 😞. Thank you so much for getting to the bottom of this. ❤️

**Comment by mkobetic** [comment]
@neekolas do you remember what happened here? I can't believe this was broken from the beginning.

**Comment by mkobetic** [comment]
OK, IIUC the decoding was broken for both versions, so the thing I'm puzzled by is how did the v1 compression test pass? Otherwise the fixes look good to me.

**Comment by nakajima** [comment]
> so the thing I'm puzzled by is how did the v1 compression test pass? 

I was wondering about that too. I don't think we have an assertion that says that anything was actually compressed to begin with in that code path. I can add some additional checks in there to make sure things are happening the way we expect. I'm glad I decided to work on adding compression to the iOS sdk today, I'm learning so much!

**Comment by nakajima** [comment]
Also the test failures don't seem super related to my changes here (they actually look similar to what's happening in https://github.com/xmtp/xmtp-js/pull/260, which is just a docs change). Any insight into what might be happening there would be super appreciated.

**Comment by mkobetic** [comment]
> > so the thing I'm puzzled by is how did the v1 compression test pass?
> 
> I was wondering about that too. I don't think we have an assertion that says that anything was actually compressed to begin with in that code path. I can add some additional checks in there to make sure things are happening the way we expect. I'm glad I decided to work on adding compression to the iOS sdk today, I'm learning so much!

Oh, I see, I think you're right. If DEFLATE turned into a noop due to the original bug you were fixing, then the compression didn't happen, and so the received content was the same as the sent content event though we didn't decompress at all. That would explain it.

**Comment by mkobetic** [comment]
> Also the test failures don't seem super related to my changes here (they actually look similar to what's happening in #260, which is just a docs change). Any insight into what might be happening there would be super appreciated.

I haven't touched the SDK in a while, I'm hoping someone else is more up to date here. But if needed I can dig into it tomorrow.

**Comment by michaelx11** [comment]
This merged PR might fix tests: https://github.com/xmtp/xmtp-js/pull/262 - try updating the branch

**Comment by nakajima** [comment]
@michaelx11 That did the trick, thanks!

**Pull request merged**
